Fix AttributeError: 'NoneType' object has no attribute 'get': `config.parse_known_args() changes `config.weighted_sampler_multipliers` from {} to None => this causes error later in vits.py - multi_dict = config.weighted_sampler_multipliers.get(attr_name, None)